
#########################
# Special Workspace
#########################
bind = SUPER, o, togglespecialworkspace, obsidian
binds = SUPER SHIFT, o&d, exec, obsidian "obsidian://daily?vault=grizzlyweb"


workspace = special:obsidian, on-created-empty:obsidian "obsidian://daily?vault=grizzlyweb"

windowrule {
  name = obsidian-scratch
  match:class = ^(obsidian)$

  workspace = special:obsidian
  float = on
  center = on
  size = (monitor_w*0.75) (monitor_h*0.90)
  opacity = 0.95
}


bind = SUPER, G, togglespecialworkspace, gaming
