
#########################
# Special Workspace
#########################
bind = SUPER, n, togglespecialworkspace, obsidian
workspace = special:obsidian, on-created-empty:xdg-open "obsidian://daily?vault=grizzlyweb"



windowrule {
  name = obsidian-scratch
  match:class = ^(obsidian)$

  workspace = special:obsidian
  float = on
  center = on
  size = (monitor_w*0.75) (monitor_h*0.90)
  # optional:
  # opacity = 0.95
  # rounding = 12
}


bind = SUPER, G, togglespecialworkspace, gaming
