
#########################
# Special Workspace
#########################
bind = SUPER, n, togglespecialworkspace, obsidian
workspace = special:obsidian, on-created-empty:xdg-open "obsidian://daily?vault=grizzlyweb"


bind = SUPER, G, togglespecialworkspace, gaming
