[pyprland]
plugins = [
    "scratchpads",
    "magnify",
]


[scratchpads.dashboard]
command = "obsidian"          # wird gestartet, falls noch nicht läuft
#unfocus = "hide"              # auto-close wenn du was anderes fokussierst
size = "1200px 90%"
position = "30% 5%"
