#!/usr/bin/env bash

DIR="$HOME/.config/hypr/monitors"
CURRENT="$DIR/current.conf"

profiles=(
  home
  work
  haupt
)

# resolve current profile
current="$(readlink "$CURRENT" 2>/dev/null | xargs -n1 basename | sed 's/\.conf$//')"

next="${profiles[0]}"
for i in "${!profiles[@]}"; do
  if [[ "${profiles[$i]}" == "$current" ]]; then
    next="${profiles[$(( (i + 1) % ${#profiles[@]} ))]}"
    break
  fi
done

ln -sf "$DIR/$next.conf" "$CURRENT"
hyprctl reload

